language: python
python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - easy_install nose

before_script:
  - "nohup python code/application.py &"
  - "sleep 10"

script:
  - make test

after_success:
  - git checkout develop
  - git pull
  - git checkout master
  - git pull origin master
  - git merge develop
  - git push origin master
