language: python
python:
  - '2.7'

install:
  - pip install -r requirements.txt
  - easy_install nose

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "nohup python code/application.py &"
  - "sleep 5"

script:
  - "nosetests tests"
  # - "cd tests"
  ## - "lettuce"

after_success:
  - git checkout develop
  - git pull
  - git checkout master
  - git pull origin master
  - git merge develop
  - git push origin master
